[[redirects]]
  from = "/docs/category/general-traffic-rules"
  to = "/docs/general-traffic-rules"

[[redirects]]
  from = "/docs/category/signs-structures"
  to = "/docs/signs-structures"

[[redirects]]
  from = "/docs/category/enforcement-penalties"
  to = "/docs/enforcement-penalties"